<?php

return [
    // Generic actions
    'save' => 'Save',
    'save_changes' => 'Save changes',
    'cancel' => 'Cancel',
    'edit' => 'Edit',
    'delete' => 'Delete',
    'remove' => 'Remove',
    'archive' => 'Archive',
    'unarchive' => 'Unarchive',
    'restore' => 'Restore',
    'create' => 'Create',
    'add' => 'Add',
    'update' => 'Update',
    'confirm' => 'Confirm',
    'continue' => 'Continue',
    'submit' => 'Submit',
    'close' => 'Close',
    'back' => 'Back',
    'next' => 'Next',
    'previous' => 'Previous',
    'view' => 'View',
    'view_all' => 'View all',
    'see_more' => 'See more',
    'show' => 'Show',
    'hide' => 'Hide',
    'open' => 'Open',
    'copy' => 'Copy',
    'copied' => 'Copied!',
    'share' => 'Share',
    'download' => 'Download',
    'upload' => 'Upload',
    'search' => 'Search',
    'filter' => 'Filter',
    'sort' => 'Sort',
    'reset' => 'Reset',
    'apply' => 'Apply',
    'enable' => 'Enable',
    'disable' => 'Disable',
    'enabled' => 'Enabled',
    'disabled' => 'Disabled',
    'on' => 'On',
    'off' => 'Off',
    'yes' => 'Yes',
    'no' => 'No',
    'all' => 'All',
    'none' => 'None',
    'optional' => 'Optional',
    'required' => 'Required',
    'select' => 'Select',
    'select_option' => 'Select an option',
    'choose' => 'Choose',
    'learn_more' => 'Learn more',
    'read_more' => 'Read more',
    'show_less' => 'Show less',
    'show_more' => 'Show more',
    'expand' => 'Expand',
    'collapse' => 'Collapse',
    'manage' => 'Manage',
    'configure' => 'Configure',
    'preview' => 'Preview',
    'send' => 'Send',
    'sending' => 'Sending…',
    'saving' => 'Saving…',
    'loading' => 'Loading…',
    'processing' => 'Processing…',
    'or' => 'Or',
    'and' => 'and',
    'untitled' => 'Untitled',
    'no_results' => 'No results found.',
    'no_data' => 'No data yet.',
    'try_again' => 'Try again',
    'go_back' => 'Go back',
    'go_home' => 'Back to PluralSpace',
    'sign_out' => 'Sign out',
    'log_out' => 'Log out',

    // Confirmation
    'are_you_sure' => 'Are you sure?',
    'this_cannot_be_undone' => 'This action cannot be undone.',
    'type_to_confirm' => 'Type :value to confirm.',

    // Status messages
    'unsaved_changes' => 'You have unsaved changes.',
    'changes_saved' => 'Changes saved.',
    'something_went_wrong' => 'Something went wrong.',
    'please_try_again' => 'Please try again.',

    // Time
    'just_now' => 'Just now',
    'today' => 'Today',
    'yesterday' => 'Yesterday',
    'tomorrow' => 'Tomorrow',
    'never' => 'Never',
    'now' => 'Now',
    'last_updated_at' => 'Last updated :time',
    'created_at' => 'Created :time',

    // Misc
    'name' => 'Name',
    'description' => 'Description',
    'email' => 'Email',
    'email_address' => 'Email address',
    'password' => 'Password',
    'confirm_password' => 'Confirm password',
    'current_password' => 'Current password',
    'new_password' => 'New password',
    'date' => 'Date',
    'time' => 'Time',
    'type' => 'Type',
    'status' => 'Status',
    'actions' => 'Actions',
    'options' => 'Options',
    'details' => 'Details',
    'settings' => 'Settings',
    'profile' => 'Profile',
    'avatar' => 'Avatar',
    'color' => 'Color',
    'icon' => 'Icon',
    'image' => 'Image',
    'visibility' => 'Visibility',
    'tags' => 'Tags',
    'notes' => 'Notes',

    // Generic shared
    'untitled_with_parens' => '(Untitled)',
    'search_groups_placeholder' => 'Search groups…',
    'no_groups_found' => 'No groups found.',

    // Errors
    'error' => 'Error',
    'warning' => 'Warning',
    'info' => 'Info',
    'success' => 'Success',
    'not_found' => 'Not found',
    'unauthorized' => 'You don\'t have permission to do that.',

    // Upload / file
    'upload_timed_out' => 'That file upload timed out. Please select the file again.',

    // Auth/sudo (ConfirmIdentity)
    'password_mismatch' => 'That password does not match our records.',
];
