<?php

return [
    // Existing fields
    'name' => 'Member name',
    'display_name' => 'Display name',
    'pronouns' => 'Pronouns',
    'created' => 'Member created.',
    'updated' => 'Member updated.',
    'deleted' => 'Member deleted.',
    'archived' => 'Member archived.',
    'unarchived' => 'Member unarchived.',
    'is_custom_front' => 'Custom front',
    'is_custom_front_description' => 'A named fronting state, not tied to a specific alter.',

    // Index page
    'index_subtitle' => 'Everyone in your :system',
    'new_member' => 'New :member',
    'add_member' => 'Add :member',
    'create_member' => 'Create :member',
    'edit_member' => 'Edit :member',
    'edit_member_title' => 'Edit :member',
    'new_member_title' => 'New :member',
    'new_member_subtitle' => 'Add someone new to your :system.',
    'edit_member_subtitle' => 'Update details for :name.',
    'back_to_members' => 'Back to :members',
    'back_to_member' => 'Back to :name',
    'search_placeholder' => 'Search :members…',
    'search_to_add_placeholder' => 'Search to add :member…',
    'search_to_tag_placeholder' => 'Search to tag a :member…',
    'no_members_found_text' => 'No :members found',
    'no_members_yet' => 'No :members yet',
    'no_members_yet_short' => 'No :members yet',
    'add_first_member_hint' => 'Add your first :system :member to get started.',
    'no_members_found_short' => 'No :members found.',

    // Filters
    'filters' => 'Filters',
    'currently_fronting' => 'Currently :fronting',
    'show_archived' => 'Show archived',
    'show_templates' => 'Show templates',
    'group_heading' => 'Group',
    'all_roles' => 'All roles',
    'all_groups' => 'All groups',
    'all_members' => 'All :members',

    // Bulk select
    'select_all' => 'Select all',
    'deselect_all' => 'Deselect all',
    'members_selected' => ':count :member selected|:count :members selected',
    'delete_count' => 'Delete :count',
    'deleting' => 'Deleting…',
    'confirm_delete_count' => 'Are you sure you want to delete :count :label?',
    'confirm_delete_member' => 'Are you sure you want to delete :name?',

    // Show page
    'template_badge' => 'Template',
    'archived_badge' => 'Archived',
    'pin_action' => 'Pin',
    'unpin_action' => 'Unpin',
    'custom_front_badge' => 'Custom :front',
    'profile_info' => 'Profile Info',
    'groups_view_tree' => 'Tree',
    'groups_view_flat' => 'Flat',
    'relationships' => 'Relationships',
    'no_relationships_yet' => 'No relationships yet.',
    'not_in_any_groups' => 'Not in any groups.',
    'add_relationship' => 'Add Relationship',
    'relationship_search_types_placeholder' => 'Search types…',
    'relationship_notes_placeholder' => 'Optional notes about this relationship…',
    'swap_direction' => 'Swap direction',
    'rel_preview_is_the' => 'is the',
    'rel_preview_of' => 'of',

    // Front modal
    'front_action_label' => ':front',
    'front_member' => ':front :name',
    'front_type' => ':front Type',
    'front_note_placeholder' => 'Write a note about this :front…',
    'leave_front' => 'Leave :front',
    'update_fronting' => 'Update :fronting',
    'start_fronting' => 'Start :fronting',
    'front_history' => ':front History',
    'delete_front_record_title' => 'Delete this :front record',

    // Form
    'avatar_preview_alt' => 'Avatar preview',
    'banner_label' => 'Banner',
    'banner_preview_alt' => 'Banner preview',
    'no_banner_set' => 'No banner set',
    'upload_photo' => 'Upload photo',
    'upload_banner' => 'Upload banner',
    'banner_help' => 'PNG, JPG, or GIF. Max 4 MB.',
    'uploading' => 'Uploading…',
    'member_color' => ':member Color',
    'name_placeholder' => 'e.g. Alex',
    'name_description' => 'The internal name used within the :system.',
    'display_name_placeholder' => 'Shown publicly if different from system name',
    'pronouns_placeholder' => 'e.g. they/them, he/him, she/her',
    'message_prefix_label' => 'Message Prefix',
    'message_prefix_placeholder' => 'e.g. A: or ~alex',
    'message_prefix_description' => 'A short prefix that auto-selects this :member when typed at the start of a message.',
    'roles_label' => 'Roles',
    'roles_placeholder' => 'Type a role and press Enter…',
    'description_placeholder' => 'A brief description about this :member…',
    'is_custom_front_checkbox' => 'This is a custom :front (not a person)',

    // Edit page extras
    'auto_save_on' => 'Auto-save on',
    'auto_save_off' => 'Auto-save off',
    'updated_flash' => 'Updated!',
    'update_member' => 'Update :name',
    'add_another' => 'Add another',
    'optional_suffix_html' => '(optional)',

    // Pin / Archive / Template / Visibility cards
    'pin_label' => 'Pin this :member to the top',
    'pin_description' => 'Pinned :members appear first in the :front selector and :member lists.',
    'visibility_description' => 'Control which roles can see this :member.',
    'archive_label' => 'Archive this :member',
    'archive_description' => 'Archived :members are hidden from most views.',
    'template_label' => 'Mark this :member as a template',
    'template_description_one' => 'Mark this :member as a template to easily add new :members.',
    'template_description_two' => 'Template :members are visible when creating a new :member.',
    'template_description_three' => 'Only base profile information is kept. No custom fields.',

    // Templates card (create page)
    'templates_heading' => 'Templates',
    'templates_intro' => 'Start with a pre-filled form to quickly create common types of :members.',
    'templates_overwrite_confirm' => 'This will overwrite any information you have already entered. Are you sure?',

    // Performed by
    'performed_by' => 'Performed by',
    'performed_by_search_placeholder' => 'Search :members…',
    'performed_by_description' => 'Which :member is performing this action?',

    // Notes (relationship notes single-word label)
    'system_map_title' => ':system Map',
    'system_map_subtitle' => 'Visualize how :members are connected',
    'filter_relationship_types_placeholder' => 'Filter relationship types…',
    'show_arrows' => 'Show arrows',
    'show_names' => 'Show names',
    'system_map_truncated_heading' => 'Showing first :limit of :total :members',
    'system_map_truncated_text' => 'The map is capped at :limit nodes for performance. Use the search field above to narrow the view. This is a temporary restriction while we work on improvements.',
    'no_members_yet_map_hint' => 'Add :members to your :system to see them on the map.',
    'pick_member_to_front' => 'Pick at least one :member to start a :front.',
    'self_relationship' => 'A :member cannot have a relationship with themselves.',
    'relationship_already_exists' => 'This relationship already exists.',
    'related_not_in_system' => 'That :member isn\'t part of this :system.',

    // Validation attribute labels
    'attr_related_member' => 'Related member',
    'attr_relationship_type' => 'Relationship type',
    'attr_group_name' => 'Group name',
    'attr_parent_group' => 'Parent group',
];
