<?php

return [
    'description' => 'Manage your account, profile, and preferences.',

    // Profile
    'profile_description' => 'Update your name and email address.',
    'profile_subheading' => 'Update your name and email address',
    'email_unverified' => 'Your email address is unverified.',
    'email_resend_link' => 'Click here to resend the verification email.',
    'email_resend_link_alt' => 'Click here to re-send the verification email.',
    'email_verification_sent' => 'A new verification link has been sent to your email address.',
    'email_change_pending' => 'Email change pending — check :email to confirm.',
    'cancel_email_change' => 'Cancel change',
    'current_password_email_description' => 'Required to change your email address.',
    'current_avatar' => 'Current avatar',
    'uploading' => 'Uploading...',
    'timezone' => 'Timezone',
    'select_timezone_placeholder' => 'Select a timezone...',
    'saved' => 'Saved.',
    'friend_code' => 'Friend Code',
    'friend_code_regenerated' => 'Regenerated.',
    'friend_code_copied' => 'Copied to clipboard.',
    'friend_code_copy_toast' => 'Friend code copied to clipboard!',
    'regenerate_friend_code' => 'Regenerate Friend Code',

    // Password
    'password_description' => 'Use a long, random password to keep your account secure.',
    'password_subheading' => 'Ensure your account is using a long, random password to stay secure',
    'password_sr_heading' => 'Password settings',
    'set_password_heading' => 'Set password',
    'update_password' => 'Update password',
    'password_updated' => 'Password updated.',
    'sign_out_other_devices' => 'Sign out of all other devices',
    'sign_out_other_devices_description' => 'Other browsers and devices you have logged in from will be signed out the next time they make a request.',
    'invalidate_tokens' => 'Invalidate API tokens and OAuth logins',
    'invalidate_tokens_description' => 'Any existing API tokens, OAuth logins, etc. will be invalidated and require re-configuration/login. Leave this unchecked if you have long-lived integrations (e.g. Home Assistant) set up.',
    'sessions_description' => 'Manage and log out your active sessions on other browsers and devices.',
    'sessions_intro' => 'If necessary, you may log out of all of your other browser sessions across all of your devices. If you feel your account has been compromised, you should also update your password.',
    'sessions_subheading' => 'Places where you\'re currently signed in',
    'this_device' => 'This device',
    'last_active' => 'Last active :time',
    'last_active_label' => 'Last active',
    'log_out_other_sessions' => 'Log out other browser sessions',
    'log_out_other_sessions_description' => 'Please enter your password to confirm you would like to log out of your other browser sessions across all of your devices.',
    'sessions_logged_out' => 'You have been logged out of your other browser sessions.',
    'no_active_sessions' => 'No active sessions.',
    'sessions_count' => ':count active session|:count active sessions',
    'sign_out_all_other_devices' => 'Sign out all other devices',
    'sign_out_all_other_devices_confirm' => 'Sign out of every other device?',
    'sign_out_device_confirm' => 'Sign this device out?',
    'unknown_ip' => 'Unknown IP',

    // API tokens
    'api_tokens_description' => 'Create personal access tokens to authenticate API requests.',
    'api_tokens_subheading' => 'Create and manage personal access tokens for API authentication',
    'create_token' => 'Create token',
    'token_name' => 'Token name',
    'token_name_placeholder' => 'e.g. My mobile app',
    'token_created' => 'Token created. Copy it now — you won\'t see it again.',
    'token_value_label' => 'Your new API token',
    'token_value_warning' => 'Make sure to copy your token now. You won\'t be able to see it again.',
    'token_revoke_confirm' => 'Revoke this token? Any application using it will lose access immediately.',
    'token_revoke_confirm_long' => 'Are you sure you want to revoke this token? Any applications using it will no longer have access.',
    'no_tokens' => 'You haven\'t created any tokens yet.',
    'no_tokens_heading' => 'No API tokens',
    'no_tokens_description' => 'Create a token above to authenticate with the API.',
    'last_used_at' => 'Last used :time',
    'last_used_label' => 'Last used',
    'existing_tokens' => 'Existing tokens',
    'done' => 'Done',

    // Authorized apps
    'authorized_apps_subheading' => 'Manage third-party applications that have access to your account',
    'authorized_apps_sr_heading' => 'Authorized applications',
    'authorized_label' => 'Authorized',
    'revoke' => 'Revoke',
    'revoke_app_confirm' => 'Are you sure you want to revoke access for :app?',
    'no_authorized_apps_heading' => 'No authorized applications',
    'no_authorized_apps_description' => 'When you authorize third-party applications to access your account, they will appear here.',

    // Connected accounts
    'connections_description' => 'Connect external accounts for faster sign-in.',
    'connections_subheading' => 'Connect or disconnect third-party accounts',
    'connections_sr_heading' => 'Connected accounts',
    'connect_provider' => 'Connect :provider',
    'disconnect_provider' => 'Disconnect :provider',
    'provider_connected' => ':provider connected.',
    'provider_disconnected' => ':provider disconnected.',
    'cannot_disconnect_only_provider' => 'Set a password before disconnecting your only sign-in method.',
    'not_connected' => 'Not connected',
    'connect' => 'Connect',
    'disconnect' => 'Disconnect',
    'disconnect_provider_confirm' => 'Are you sure you want to disconnect your :provider account?',
    'primary_login' => 'Primary login',

    // Notification preferences
    'notifications_description' => 'Choose which notifications you want to receive and how.',
    'notifications_subheading' => 'Control how you receive notifications for different events',
    'notifications_sr_heading' => 'Notification settings',
    'channel_push' => 'Push',
    'channel_inapp' => 'In-app',
    'enable_push' => 'Enable push notifications',
    'disable_push' => 'Disable push notifications',
    'push_blocked' => 'Push notifications are blocked in your browser settings.',
    'push_enabled' => 'Push notifications enabled on this device.',
    'preferences_saved' => 'Notification preferences saved.',
    'browser_notifications_heading' => 'Browser notifications on this device',
    'browser_notifications_description' => 'Push notifications need to be enabled separately on each browser and device you use.',
    'checking_status' => 'Checking status...',
    'unsupported_browser' => 'This browser doesn\'t support push notifications. On iOS, add PluralSpace to your home screen and open it from there to enable them.',
    'browser_registered' => 'This browser is registered for push notifications.',
    'notifications_blocked' => 'Notifications are blocked for this browser. You\'ll need to enable them in your browser or iOS settings — deleting and reinstalling the app won\'t reset this.',
    'how_to_re_enable' => 'How to re-enable notifications',
    'browser_not_registered' => 'This browser hasn\'t been registered yet. Click below to enable push notifications here.',
    'enable_notifications' => 'Enable notifications',
    'asking_browser' => 'Asking browser...',
    'help' => 'Help',
    'prompt_dismissed' => 'The prompt was dismissed or denied. If no prompt appeared, try the help link — iOS doesn\'t always re-prompt.',
    'permission_granted_not_subscribed' => 'Permission is granted, but this browser isn\'t subscribed yet. Click below to finish setup.',
    'register_this_browser' => 'Register this browser',
    'registering' => 'Registering...',
    'system_notifications_heading' => 'System notifications',
    'system_notifications_description' => 'Choose which systems you want to receive notifications from. Disabling a system mutes all notifications from it.',

    // Appearance
    'appearance_description' => 'Choose how PluralSpace looks to you.',
    'appearance_subheading' => 'Update the appearance settings for your account',
    'appearance_sr_heading' => 'Appearance settings',
    'appearance_wip_title' => 'Work in Progress',
    'appearance_wip_line1' => 'The appearance settings are still a work in progress. You make experience some issues or strange colors.',
    'appearance_wip_line2' => 'We are actively working on improving this feature and we appreciate your patience and understanding.',

    // Systems (multi-system management)
    'systems_title' => 'Your systems',
    'systems_description' => 'Switch between systems you belong to or create a new one.',
    'systems_subheading' => 'Manage the systems you belong to',
    'create_system' => 'Create a new system',
    'leave_system' => 'Leave system',
    'leave' => 'Leave',
    'leave_system_confirm' => 'Are you sure you want to leave :system?',
    'current' => 'Current',
    'no_member_of_systems' => 'You are not a member of any systems.',

    // 2FA section (settings page wrapper)
    'two_factor_subheading' => 'Manage your two-factor authentication settings',
    'two_factor_sr_heading' => 'Two-factor authentication settings',

    // Delete account
    'delete_account_description' => 'Permanently delete your account and all data associated with it.',
    'delete_account_subheading' => 'Delete your account and all of its resources',
    'delete_account_warning' => 'Once your account is deleted, all of its resources and data will be permanently deleted. This cannot be undone.',
    'delete_account_confirm_title' => 'Are you sure you want to delete your account?',
    'delete_account_confirm_description' => 'Once your account is deleted, all of its resources and data will be permanently deleted. Please enter your password to confirm.',
    'delete_account_confirm_description_long' => 'Once your account is deleted, all of its resources and data will be permanently deleted. Please enter your password to confirm you would like to permanently delete your account.',

    // Livewire flash messages
    'token_revoked' => 'Token revoked.',
    'session_signed_out' => 'Session signed out.',
    'all_other_devices_signed_out' => 'All other devices signed out.',
    'access_revoked' => 'Access revoked.',
    'connections_only_login_method' => 'This is your only login method. Please set a password or connect another provider before disconnecting.',
    'provider_disconnected_short' => ':provider account disconnected.',
];
