<?php

return [
    // Existing keys
    'name' => 'System name',
    'created' => 'System created.',
    'updated' => 'System updated.',
    'deleted' => 'System deleted.',
    'switch' => 'Switch system',

    // Common
    'settings_subheading' => 'Manage your :system profile and privacy',
    'term_color' => ':term color',
    'term_name' => ':term name',
    'term_name_placeholder' => 'My :term',
    'slug' => 'Slug',
    'slug_placeholder' => 'my-:term',
    'slug_description' => 'Used in public URLs. Lowercase letters, numbers, and hyphens only.',
    'description_placeholder' => 'A short description about your :term...',

    // Customize Your Space
    'customize_your_space' => 'Customize Your Space',
    'customize_your_space_description' => 'Turn sections of PluralSpace on or off for your :term. Some features can be overwhelming or triggering, so you get to choose what shows up. Changes save automatically. Turning something off hides it from the sidebar and pages, but nothing is deleted — you can turn it back on any time and your data will still be there.',
    'show_feature' => 'Show :name',

    // Danger zone
    'delete_intro' => 'Permanently delete this :system and all of its data. This action cannot be undone.',
    'delete_will_remove' => 'This will permanently delete:',
    'delete_item_members' => 'All :members and their profiles, avatars, and custom field data',
    'delete_item_fronts' => 'All :front history and :front types',
    'delete_item_journal' => 'All journal entries',
    'delete_item_polls' => 'All polls and votes',
    'delete_item_chat' => 'All chat channels and messages',
    'delete_item_groups' => ':Member groups, relationships, and relationship types',
    'delete_item_fields' => 'Custom fields and permission settings',
    'delete_item_profile' => 'Your public profile page',
    'delete_item_logs' => 'Activity logs, data exports, and invitations',
    'delete_button' => 'Delete :system',
    'delete_confirm_prompt' => 'Are you sure?\n\nYou want to delete :name? This action can NOT be undone.\n\nType DELETE to confirm.|DELETE',

    // Permissions
    'permissions_subheading' => 'Configure what each role can do in your :system',
    'role_permissions' => 'Role Permissions',
    'role_permissions_description' => 'Toggle permissions for each role. Owner always has full access.',
    'permission' => 'Permission',
    'save_all' => 'Save All',
    'all_permissions_saved' => 'All permissions saved.',
    'permission_label_for_role' => ':permission for :role',

    // Users
    'users_subheading' => 'Who has access to this :system',
    'invite_user' => 'Invite User',
    'users_count' => ':count user|:count users',
    'you_suffix' => '(you)',
    'remove_user_confirm' => 'Remove :name from this :system?',
    'pending_count' => ':count pending',
    'pending_invitations' => 'Pending Invitations',
    'invited_by_expires' => 'Invited by :inviter · expires',
    'cancel_invitation_confirm' => 'Cancel this invitation for :email?',
    'invite_email_label' => 'Email address or Friend Code',
    'invite_email_placeholder' => 'someone@example.com or ABCD-1234',
    'invite_role_description_html' => '<strong>Owner</strong> can manage everything. <strong>Trusted</strong> can read and write. <strong>View only</strong> can read.',
    'invite_role_owner_label' => 'Owner',
    'invite_role_owner_text' => 'can manage everything.',
    'invite_role_trusted_label' => 'Trusted',
    'invite_role_trusted_text' => 'can read and write.',
    'invite_role_view_only_label' => 'View only',
    'invite_role_view_only_text' => 'can read.',
    'send_invite' => 'Send Invite',

    // Terminology
    'terminology_subheading' => 'Customize the words used throughout your :system',
    'terminology_intro' => 'Customize the words used throughout your space. Changes are reflected everywhere for all users of this :system.',
    'quick_presets' => 'Quick presets',
    'member_term' => 'Member term',
    'front_term' => 'Front term',
    'fronting_term' => 'Fronting term',
    'system_term' => 'System term',
    'plural_label' => 'Plural: :plural',
    'fronting_description' => 'Used as a verb/status, e.g. "Who is :fronting?"',
    'preview_members_page' => 'Your :members page',
    'preview_who_is_fronting' => 'Who is :fronting?',
    'preview_system_settings' => ':system settings',
    'preview_add_member' => 'Add a new :member',

    // Custom fields
    'custom_fields_subheading' => 'Extra information shown on each :member profile',
    'add_field' => 'Add Field',
    'fields_label' => 'Fields',
    'fields_count' => ':count field|:count fields',
    'no_fields_yet' => 'No custom fields yet. Add one to display extra information on :member profiles.',
    'multiple_badge' => 'Multiple',
    'delete_field_confirm' => 'Delete the field ":name"? All :member values for this field will also be deleted.',
    'edit_field' => 'Edit Field',
    'add_custom_field' => 'Add Custom Field',
    'field_name' => 'Field name',
    'field_name_placeholder' => 'e.g. Favorite Color',
    'field_type' => 'Field type',
    'editor_warning_title' => 'Heads up!',
    'editor_warning_text' => 'Existing content will be automatically converted. Some formatting details like custom colors, alignment, or images may not transfer perfectly between editors. Apologies in advance if you need to do some manual cleanup after changing!',
    'allow_multiple_values' => 'Allow multiple values',
    'allow_multiple_values_description' => ':members can add more than one entry for this field.',
    'visibility_min_role_description' => 'Minimum role required to see this field on :member profiles.',
    'front_types_heading' => ':front Types',
    'front_types_subheading' => 'Customize the types of :front available in your :system',
    'add_type' => 'Add Type',
    'front_types_label' => ':front Types',
    'types_count' => ':count type|:count types',
    'no_front_types' => 'No :front types configured yet.',
    'default_badge' => 'Default',
    'delete_front_type_confirm' => 'Delete the type ":name"? Existing :front records using this type will be reassigned to the default type.',
    'edit_front_type' => 'Edit :front Type',
    'add_front_type' => 'Add :front Type',
    'name_placeholder_front_type' => 'e.g. Little Front',
    'hex_placeholder' => '#7c3aed',
    'color_description' => 'Used for the ring color and badges when this type is active.',
    'emoji_optional' => 'Emoji (optional)',
    'emoji_placeholder' => 'e.g. ✦ ⚡ 🌙 💫',
    'emoji_description' => 'Displayed alongside the type name in the :front panel.',

    // Member groups
    'member_groups_heading' => ':member Groups',
    'member_groups_subheading' => 'Organize :members into groups for easy filtering',
    'add_group' => 'Add Group',
    'no_groups_yet' => 'No groups yet. Create one to organize your :members.',
    'edit_group' => 'Edit Group',
    'group_name_placeholder' => 'e.g. Protectors',
    'parent_group_none' => 'None (top-level)',
    'group_description_placeholder' => 'A brief description for this group...',
    'manage_group_members' => ':group :members',
    'no_members_in_group' => 'No :members in this group yet.',
    'search_members_to_add' => 'Search :members to add...',
    'add_subgroup' => 'Add subgroup',
    'manage_members_action' => 'Manage :members',
    'delete_group_confirm' => 'Delete the group ":name"?:children_note :Members will be removed from this group but not deleted.',
    'delete_group_subgroups_note' => ' Subgroups will be promoted to the parent level.',
    'subgroups_count' => ':count subgroup|:count subgroups',
    'members_count' => ':count :member|:count :members',
    // Relationship types
    'relationship_types_subheading' => 'Define the types of relationships between :members',
    'preset_types' => 'Preset Types',
    'no_preset_types' => 'No preset types available.',
    'inverse_label' => 'Inverse: :name',
    'reciprocal_badge' => 'Reciprocal',
    'preset_badge' => 'Preset',
    'custom_types' => 'Custom Types',
    'no_custom_types' => 'No custom types yet. Create one to define your own relationship categories.',
    'relationships_count' => ':count relationship|:count relationships',
    'edit_relationship_type' => 'Edit Relationship Type',
    'add_relationship_type' => 'Add Relationship Type',
    'relationship_name_placeholder' => 'e.g. Protector',
    'relationship_name_description' => 'The label for the forward direction of this relationship.',
    'inverse_name_label' => 'Inverse name',
    'inverse_name_placeholder' => 'e.g. Protectee',
    'inverse_name_description' => 'The label for the reverse direction (e.g. if A is "Parent" of B, then B is "Child" of A).',
    'reciprocal_description' => 'Reciprocal relationships show as a two-way connection on the map (e.g. Partner, Sibling, Friend).',
    'icon_placeholder' => 'e.g. 💕 🛡️ 👫',
    'icon_description' => 'An emoji shown on the system map instead of the type name.',
    'delete_relationship_type_title' => 'Delete :name?',
    'relationship_type_in_use_heading' => 'This relationship type is in use',
    'relationship_type_in_use_text' => 'It\'s currently applied to :count :label. Deleting this type will also remove :pronoun. This cannot be undone.',
    'relationship_type_pronoun' => 'that relationship|those relationships',
    'relationship_type_label' => ':member relationship|:member relationships',
    'relationship_type_unused_text' => 'This type isn\'t used by any :member relationships. This cannot be undone.',
    'delete_type_and_relationships' => 'Delete type and relationships',
    'delete_type' => 'Delete type',

    // Profile settings (public profile)
    'public_profile_subheading' => 'Configure how your :system appears publicly',
    'public_profiles_early_access' => 'Public Profiles — Early Access',
    'public_profiles_early_access_text' => 'Public profiles are currently being rolled out gradually. Request access and we\'ll review your :system for eligibility.',
    'request_pending_badge' => 'Request Pending',
    'request_pending_note' => 'We\'ll notify you once your request is reviewed.',
    'request_access' => 'Request Access',
    'request_submitted' => 'Request submitted.',
    'access_revoked_heading' => 'Public Profile Access Revoked',
    'access_revoked_text' => 'Your public profile has been disabled due to a Terms of Service violation. Please contact support if you believe this is an error.',
    'enable_public_profile' => 'Enable Public Profile',
    'profile_live' => 'Your profile is live and publicly accessible.',
    'profile_hidden' => 'Your profile is currently hidden from the public.',
    'your_profile_url' => 'Your profile URL',
    'profile_slug_label' => 'Profile Slug',
    'profile_slug_placeholder' => 'your-system',
    'profile_slug_description' => 'Letters, numbers, dashes, and underscores only.',
    'layout' => 'Layout',
    'primary_color' => 'Primary Color',
    'accent_color' => 'Accent Color',
    'background_color' => 'Background Color',
    'text_color' => 'Text Color',
    'font_family' => 'Font Family',
    'spacing' => 'Spacing',
    'border_radius' => 'Border Radius',
    'theme_preview_name' => ':system Name',
    'theme_preview_text' => 'This is how your profile text will look.',
    'theme_preview_accent' => 'Accent text sample',
    'custom_css' => 'Custom CSS',
    'custom_styles' => 'Custom Styles',
    'custom_styles_description' => 'Add custom CSS to further customize your public profile appearance.',
    'member_visibility' => ':member Visibility',
    'set_all' => 'Set all...',
    'search_members_dotdotdot' => 'Search :members...',
    'no_members_matching' => 'No :members found matching ":query".',
    'no_active_members' => 'No active :members to configure.',
    'field_visibility_overrides' => 'Field Visibility Overrides',
    'use_default' => 'Use Default',

    // Data export
    'data_export_subheading' => 'Request and download exports of your :system data',
    'about_data_export' => 'About your data export',
    'gdpr_notice' => 'In accordance with GDPR Article 15 (Right of Access) and CCPA, you can request a copy of all data stored in your current :system. This includes: :system information, :members, :fronting history, journal entries, chat messages, polls, thoughts of the day, :member groups, custom fields, and associated media files. Private journal entries are included only in your own exports.',
    'request_new_export_for' => 'Request new export for',
    'export_format' => 'Export format',
    'export_format_json' => 'JSON — Machine-readable format, ideal for data portability (GDPR Article 20)',
    'export_format_html' => 'HTML — Human-readable format with styled pages, ideal for personal review',
    'export_in_progress' => 'You already have an export in progress. Please wait for it to complete before requesting a new one.',
    'request_export' => 'Request export',
    'export_history' => 'Export history',
    'export_label' => 'Export',
    'pending' => 'Pending',
    'processing' => 'Processing',
    'completed' => 'Completed',
    'failed' => 'Failed',
    'expired' => 'Expired',
    'requested' => 'Requested',
    'size_label' => 'Size: :size',
    'expires_label' => 'Expires',
    'delete_export_confirm' => 'Are you sure you want to delete this export?',
    'no_exports_yet' => 'No exports yet',
    'no_exports_description' => 'Request an export above to download a copy of your :system data.',

    // Imports — index
    'import_subheading' => 'Choose how you\'d like to bring your data into PluralSpace',
    'sp_export_file' => 'SimplyPlural Export File',
    'sp_export_file_description' => 'Upload a JSON export file from SimplyPlural to import your data.',
    'sp_api' => 'SimplyPlural API',
    'sp_api_description' => 'Connect your SimplyPlural token and sync data automatically.',
    'octocon_export_file' => 'Octocon Export File',
    'octocon_export_file_description' => 'Upload a JSON export file from Octocon to import your data.',

    // SP Import
    'sp_import_subheading' => 'Upload a JSON export to migrate your :members, groups, and history',
    'octocon_import_subheading' => 'Upload a JSON export to migrate your :members, tags, and history',
    'upload_export_file' => 'Upload your export file',
    'how_to_export_sp' => 'How to export from SimplyPlural',
    'how_to_export_octocon' => 'How to export from Octocon',
    'sp_step_1' => '1. Open SimplyPlural and go to <strong>Settings -> Account</strong>',
    'sp_step_3' => '3. Wait for the email to come in.',
    'sp_step_4' => '3. Download the <code class="rounded bg-violet-100 px-1 text-xs dark:bg-ps-600">.json</code> file and upload it below',
    'octocon_step_1' => '1. Open Octocon and go to <strong>Settings -> Data</strong>',
    'octocon_step_2' => '2. Tap <strong>Export your data</strong>',
    'octocon_step_3' => '3. Save the <code class="rounded bg-violet-100 px-1 text-xs dark:bg-ps-600">.json</code> file and upload it below',
    'choose_json_file' => 'Click to choose your JSON file',
    'or_drag_drop' => 'or drag and drop it here',
    'analysing_export' => 'Analysing export…',
    'what_we_found' => 'What we found',
    'select_sections_intro' => 'Select the sections you\'d like to import. Existing data will not be overwritten.',
    'sp_privacy_notice_title' => 'Privacy tiers from SimplyPlural are not imported.',
    'sp_privacy_notice_text' => 'PluralSpace uses a role-based permission system where the :system owner configures what each role can access. This approach avoids edge cases and simplifies permission management.',
    'octocon_tags_notice_title' => 'Octocon tags become PluralSpace groups.',
    'octocon_tags_notice_text' => 'Tag hierarchy (parent/child) is preserved, and :members assigned to a tag will be added to the matching group.',
    'avatars_notice_title' => ':member avatars may not all transfer.',
    'avatars_notice_text' => 'We\'ll try to pull avatars from the original source, but some services require authentication or block external requests. Any avatars that can\'t be downloaded will use a generated fallback instead.',
    'records_count' => ':count record found|:count records found',
    'nothing_to_import' => 'Nothing to import',
    'run_import' => 'Run Import',
    'submitting' => 'Submitting…',
    'choose_different_file' => 'Choose a different file',
    'import_in_progress' => 'Import in progress',
    'import_in_progress_text' => 'Your data is being imported in the background. This page will update automatically when complete.',
    'import_finished_with_errors' => 'Import finished with some errors',
    'import_complete' => 'Import complete!',
    'import_summary_intro' => 'Here\'s a summary of what was imported into your :system.',
    'duplicates_skipped' => ':count duplicate skipped|:count duplicates skipped',
    'view_members' => 'View :members',
    'import_another_file' => 'Import another file',
    'import_history' => 'Import history',
    'history_partial' => 'Partial',
    'history_complete' => 'Complete',
    'history_by' => 'by :name',
    'history_unknown_user' => 'Unknown',

    // SP API Sync
    'sp_api_subheading' => 'Connect to SimplyPlural and sync your data automatically',
    'api_key' => 'API Key',
    'api_key_configured' => 'API key configured',
    'remove_api_key' => 'Remove key',
    'remove_api_key_confirm' => 'Are you sure you want to remove your API key? This will stop automatic syncing.',
    'api_key_removed' => 'Key removed.',
    'how_to_get_api_key' => 'How to get your API key',
    'sp_api_step_1' => '1. Open SimplyPlural and go to <strong>Settings</strong>',
    'sp_api_step_2' => '2. Find the <strong>Tokens</strong> section',
    'sp_api_step_3' => '3. Create a new token and copy it',
    'sp_api_step_4' => '4. Paste it below',
    'sp_api_key_label' => 'SimplyPlural API Key',
    'sp_api_key_placeholder' => 'Paste your API key here',
    'save_api_key' => 'Save API Key',
    'sync_data' => 'Sync Data',
    'early_access' => 'Early Access',
    'sp_sync_early_access_text' => 'This syncing feature is in early stages of development. It should work fine but may have some bugs.',
    'sp_sync_discord_note' => 'If you encounter any, we are alerted automatically. If you report it on our :discord_link, please remember to not post anything personal or any API tokens.',
    'sync_failed' => 'Sync failed',
    'last_synced' => 'Last synced :time',
    'never_synced' => 'Never synced',
    'no_api_key_configured' => 'No API key configured',
    'syncing' => 'Syncing...',
    'last_sync_did_not_complete' => 'Your last sync did not complete successfully.',
    'last_sync_resume_text' => 'Any data that was imported before the failure has been saved. You can try syncing again — it will pick up where it left off.',
    'retry_sync' => 'Retry Sync',
    'sync_now' => 'Sync Now',
    'starting_sync' => 'Starting sync...',
    'sync_running' => 'Sync running!',
    'cancel_sync' => 'Cancel sync',
    'cancel_sync_confirm' => 'Are you sure you want to cancel this sync? Any data already imported has been saved.',
    'add_api_key_to_sync' => 'Add an API key above to enable syncing.',
    'sync_cooldown' => 'You can sync again in :time.',

    // Users management (Livewire flash + errors)
    'invite_friend_code_invalid' => 'Please enter a valid email address or friend code.',
    'invite_already_member' => 'This person is already part of this :system.',
    'invite_sent_pending' => 'Invitation sent — they will appear in the list of pending invitations until they accept.',
    'cannot_change_only_owner_role' => 'You\'re the only owner, so your role can\'t be changed right now.',
    'cannot_remove_self' => 'You can\'t remove yourself from the :system.',
    'leave_only_owner' => 'You\'re the only owner — transfer ownership or delete the :system before leaving.',
    'left_system_success' => 'You have left :system.',

    // Permissions
    'permission_requires_dependency' => ':perm requires :req for :role.',

    // Member groups
    'group_max_depth' => 'Groups cannot be nested more than 3 levels deep.',
    'group_self_parent' => 'A group cannot be its own parent.',
    'group_circular' => 'A group cannot be nested under one of its own children.',

    // Mood log message ("Updated headspace mood to :mood")
    'log_updated_mood' => 'Updated headspace mood to :mood',

    // Settings save log messages
    'log_updated_settings' => 'Updated system settings',
    'log_updated_features' => 'Updated enabled features',

    // Sync messages
    'sync_one_minute' => '1 minute',
    'sync_minutes' => ':minutes minutes',

    // Data export
    'data_export_in_progress_error' => 'An export is already in progress. Please wait for it to finish.',
    'data_export_requested' => 'Your data export has been requested and is being processed.',
    'data_export_unavailable' => 'This export isn\'t available for download right now.',
    'data_export_file_missing' => 'We couldn\'t find that export file. It may have expired.',
    'data_export_deleted' => 'Export deleted.',
];
