<?php

return[
  "browse_all" => "Browse All Articles",
  "browse_category_articles" => "Browse :category articles in the PluralSpace Help Center.",
  "categories" => "Categories",
  "description" => "Guides and tutorials on how to use PluralSpace.",
  "dislike_aria" => "Mark this article as not helpful",
  "dislike_title" => "Not helpful",
  "featured_articles" => "Featured Articles",
  "footer_discord" => "Discord",
  "footer_privacy" => "Privacy",
  "footer_status" => "Status",
  "footer_terms" => "Terms",
  "help_center" => "Help Center",
  "last_updated" => "Last updated :date",
  "like_aria" => "Like this article",
  "no_articles_in_category" => "No articles in this category yet.",
  "no_categories" => "No categories available.",
  "no_results" => "No articles found matching your search.",
  "read_in_help_center" => "Read :title in the PluralSpace Help Center.",
  "recent_articles" => "Recent Articles",
  "related_articles" => "Related articles",
  "result" => "result",
  "results" => "results",
  "results_for" => ":count :results for \":query\"",
  "search" => "Search",
  "search_breadcrumb" => "Search",
  "search_placeholder" => "Search articles...",
  "status_center" => "Status Center",
  "tagline" => "A cozy, safe home for your system.",
  "tags_label" => "Tags:",
  "title" => "Help Center",
  "view_all" => "View All",
  "was_this_helpful" => "Was this helpful?"
];