<?php

return[
  "changed_front_type" => "changed from :old to :new.",
  "co_con" => "Co-con",
  "co_fronting" => "Co-fronting",
  "comment" => "Comentario",
  "current" => "Currently fronting",
  "default_member_name" => "Someone",
  "delete_record_title" => "Delete this :front record",
  "duration" => "Duration",
  "ended_at" => "Terminado en",
  "front_action" => ":front",
  "front_member" => ":front :name",
  "front_type_heading" => ":front Type",
  "history" => "Historial del frente",
  "history_heading" => ":front History",
  "leave_front" => "Leave :front",
  "log_changed_to" => ":member changed to :type",
  "log_started_front_for" => ":member started :type",
  "log_stopped_fronting" => ":member stopped fronting",
  "none" => "Nadie esta actualmente al frente.",
  "note_placeholder" => "Write a note about this :front…",
  "start_fronting" => "Start :fronting",
  "started" => "Frente añadido",
  "started_at" => "Empezado en",
  "started_fronting" => "ahora está en el frente.",
  "stopped_fronting" => "has left front.",
  "update_fronting" => "Update :fronting"
];