<?php

return[
  "browse_all" => "Explorar todos los artículos",
  "browse_category_articles" => "Explora los artículos de :category en el Centro de ayuda de PluralSpace.",
  "categories" => "Categorías",
  "description" => "Guías y tutoriales sobre cómo utilizar PluralSpace.",
  "dislike_aria" => "Marcar este artículo como no útil",
  "dislike_title" => "No fue útil",
  "featured_articles" => "Artículos destacados",
  "footer_discord" => "Discord",
  "footer_privacy" => "Privacidad",
  "footer_status" => "Estado",
  "footer_terms" => "Términos",
  "help_center" => "Centro de ayuda",
  "last_updated" => "Última actualización: :date",
  "like_aria" => "Marcar este artículo como útil",
  "no_articles_in_category" => "Aún no hay artículos en esta categoría.",
  "no_categories" => "No hay categorías disponibles.",
  "no_results" => "No se encontraron artículos para tu búsqueda.",
  "read_in_help_center" => "Leer :title en el Centro de ayuda de PluralSpace.",
  "recent_articles" => "Artículos recientes",
  "related_articles" => "Artículos relacionados",
  "result" => "resultado",
  "results" => "resultados",
  "results_for" => ":count :results para \":query\"",
  "search" => "Buscar",
  "search_breadcrumb" => "Búsqueda",
  "search_placeholder" => "Buscar artículos...",
  "status_center" => "Centro de estado",
  "tagline" => "Un hogar cálido y seguro para tu sistema.",
  "tags_label" => "Etiquetas:",
  "title" => "Centro de ayuda",
  "view_all" => "Ver todo",
  "was_this_helpful" => "¿Te resultó útil?"
];