<?php

return[
  "browse_all" => "Bekijk alle artikelen",
  "browse_category_articles" => "Browse :category articles in the PluralSpace Help Center.",
  "categories" => "Categorieën",
  "description" => "Handleidingen en tutorials over het gebruik van PluralSpace.",
  "dislike_aria" => "Markeer dit artikel als niet nuttig",
  "dislike_title" => "Niet nuttig",
  "featured_articles" => "Featured Articles",
  "footer_discord" => "Discord",
  "footer_privacy" => "Privacy",
  "footer_status" => "Status",
  "footer_terms" => "Voorwaarden",
  "help_center" => "Helpcentrum",
  "last_updated" => "Laatst bijgewerkt :date",
  "like_aria" => "Vind ik leuk",
  "no_articles_in_category" => "Er zijn nog geen artikelen in deze categorie.",
  "no_categories" => "Geen categorieën beschikbaar",
  "no_results" => "Er zijn geen artikelen gevonden die aan uw zoekopdracht voldoen.",
  "read_in_help_center" => "Read :title in the PluralSpace Help Center.",
  "recent_articles" => "Recente artikelen",
  "related_articles" => "Gerelateerde artikelen",
  "result" => "result",
  "results" => "results",
  "results_for" => ":count :results for \":query\"",
  "search" => "Search",
  "search_breadcrumb" => "Search",
  "search_placeholder" => "Search articles...",
  "status_center" => "Status Center",
  "tagline" => "A cozy, safe home for your system.",
  "tags_label" => "Tags:",
  "title" => "Help Center",
  "view_all" => "View All",
  "was_this_helpful" => "Was this helpful?"
];