<?php

return[
  "all_notes" => "Alle notities",
  "back_to_note" => "Back to Note",
  "back_to_notes" => "Back to Notes",
  "content_placeholder" => "Write your note here… Markdown is supported.",
  "create_note" => "New note",
  "created" => "Note created.",
  "created_by" => "Created by :name",
  "delete_confirm" => "Delete this note? This cannot be undone.",
  "delete_note" => "Delete note",
  "delete_note_button" => "Delete Note",
  "delete_note_confirm_html" => "This will delete :title. This action cannot be undone.",
  "delete_note_modal_heading" => "Delete Note?",
  "deleted" => "Note deleted.",
  "description" => "Shared notes for your system.",
  "edit_note" => "Edit note",
  "edit_note_subtitle_prefix" => "Created",
  "edit_note_title" => "Edit Note",
  "index_subtitle" => "Your :system's notes",
  "last_edited_by" => "Last edited by :name",
  "new_note" => "New Note",
  "no_member_option" => "No :member",
  "no_member_tagged" => "No :member tagged",
  "no_notes" => "No notes yet.",
  "no_notes_found" => "No notes found",
  "no_notes_hint" => "Notes are a place for your system to keep shared thoughts, reminders, and ideas.",
  "no_notes_hint_index" => "Notes will appear here once created.",
  "no_notes_search_hint" => "Try adjusting your search.",
  "no_notes_yet_short" => "No notes yet",
  "note_content_placeholder" => "Write your note…",
  "note_pin" => "Pin to top",
  "note_title_placeholder" => "Title…",
  "pinned_flash" => "Note pinned.",
  "save_note" => "Save Note",
  "search_notes_placeholder" => "Search notes…",
  "singular" => "Note",
  "tag_member_label" => "Tag a :member",
  "this_note" => "this note",
  "title_placeholder" => "Give this note a title…",
  "unpinned_flash" => "Note unpinned.",
  "untitled_note" => "Untitled note",
  "updated" => "Note updated.",
  "visibility_description" => "Minimum role required to see this note."
];