<?php

return[
  "back_to_entry" => "Tillbaka till inlägget",
  "back_to_journal" => "Tillbaka till journalen",
  "content" => "Innehåll",
  "content_placeholder" => "Skriv ditt inlägg här… Markdown stöds.",
  "created" => "Journalinlägg skapat.",
  "date_description" => "Vilket datum inlägget gäller för — lämnas tomt för 'nu'.",
  "delete_entry_confirm" => "Vill du radera detta journalinlägg? Detta kan inte ångras.",
  "deleted" => "Journalinlägg borttaget.",
  "edit_entry" => "Redigera inlägg",
  "edit_entry_subtitle_prefix" => "Skrivet",
  "encrypted_notice" => "Journalinlägg är krypterade och kan endast läsas av ditt system.",
  "index_subtitle" => "Ditt :systems inlägg",
  "markdown_supported" => "Markdown stöds",
  "new_entry" => "Nytt inlägg",
  "new_entry_subtitle" => "Skriv ner något.",
  "no_entries_found" => "Inga inlägg hittades",
  "no_entries_hint" => "Börja skriva för att dokumentera vad som händer.",
  "no_entries_yet" => "Inga inlägg än",
  "private" => "Privat",
  "save_entry" => "Spara inlägg",
  "search_entries_placeholder" => "Sök bland inlägg…",
  "shared" => "Delad",
  "tag_members_label" => "Tagga :members",
  "title" => "Titel",
  "title_placeholder" => "Ge inlägget en titel…",
  "untitled_entry" => "(Namnlöst inlägg)",
  "updated" => "Journalinlägg uppdaterat.",
  "visibility_description" => "Minsta roll som krävs för att se detta inlägg."
];