<?php

return[
  "browse_all" => "Bläddra bland alla artiklar",
  "browse_category_articles" => "Bläddra bland :category-artiklar i PluralSpace hjälpcenter.",
  "categories" => "Kategorier",
  "description" => "Guider och manualer för hur du använder PluralSpace.",
  "dislike_aria" => "Markera artikeln som inte hjälpsam",
  "dislike_title" => "Inte hjälpsam",
  "featured_articles" => "Utvalda artiklar",
  "footer_discord" => "Discord",
  "footer_privacy" => "Integritet",
  "footer_status" => "Status",
  "footer_terms" => "Villkor",
  "help_center" => "Hjälpcenter",
  "last_updated" => "Senast uppdaterad :date",
  "like_aria" => "Gilla den här artikeln",
  "no_articles_in_category" => "Det finns inga artiklar i den här kategorin än.",
  "no_categories" => "Inga kategorier tillgängliga.",
  "no_results" => "Inga artiklar hittades som matchar din sökning.",
  "read_in_help_center" => "Läs :title i PluralSpace hjälpcenter.",
  "recent_articles" => "Senaste artiklarna",
  "related_articles" => "Relaterade artiklar",
  "result" => "resultat",
  "results" => "resultat",
  "results_for" => ":count :results för \":query\"",
  "search" => "Sök",
  "search_breadcrumb" => "Sök",
  "search_placeholder" => "Sök efter artiklar...",
  "status_center" => "Statuscenter",
  "tagline" => "Ett mysigt och tryggt hem för ditt system.",
  "tags_label" => "Taggar:",
  "title" => "Hjälpcenter",
  "view_all" => "Visa alla",
  "was_this_helpful" => "Hjälpte det här dig?"
];