<?php

return [
  "all_notes" => "Alla anteckningar",
  "back_to_note" => "Tillbaka till anteckningen",
  "back_to_notes" => "Tillbaka till anteckningar",
  "content_placeholder" => "Skriv din anteckning här… Markdown stöds.",
  "create_note" => "Ny anteckning",
  "created" => "Anteckning skapad.",
  "created_by" => "Skapad av :name",
  "delete_confirm" => "Radera denna anteckning? Detta kan inte ångras.",
  "delete_note" => "Radera anteckning",
  "delete_note_button" => "Radera anteckning",
  "delete_note_confirm_html" => "Detta kommer radera :title. Denna åtgärd kan inte ångras.",
  "delete_note_modal_heading" => "Radera anteckning?",
  "deleted" => "Anteckning raderad.",
  "description" => "Delade anteckningar för ditt system.",
  "edit_note" => "Redigera anteckning",
  "edit_note_subtitle_prefix" => "Skapad",
  "edit_note_title" => "Redigera anteckning",
  "index_subtitle" => "Anteckningar för :system",
  "last_edited_by" => "Senast redigerad av :name",
  "new_note" => "Ny anteckning",
  "no_member_option" => "Ingen :member",
  "no_member_tagged" => "Ingen :member taggad",
  "no_notes" => "Inga anteckningar än.",
  "no_notes_found" => "Inga anteckningar hittades",
  "no_notes_hint" => "Anteckningar är en plats där ditt system kan spara delade tankar, påminnelser och idéer.",
  "no_notes_hint_index" => "Anteckningar kommer att visas här när de har skapats.",
  "no_notes_search_hint" => "Prova att justera din sökning.",
  "no_notes_yet_short" => "Inga anteckningar än",
  "note_content_placeholder" => "Skriv din anteckning…",
  "note_pin" => "Fäst högst upp",
  "note_title_placeholder" => "Titel…",
  "pinned_flash" => "Anteckning fastnålad.",
  "save_note" => "Spara anteckning",
  "search_notes_placeholder" => "Sök anteckningar…",
  "singular" => "Anteckning",
  "tag_member_label" => "Tagga en :member",
  "this_note" => "denna anteckning",
  "title_placeholder" => "Ge anteckningen en titel…",
  "unpinned_flash" => "Anteckning bortnålad.",
  "untitled_note" => "Namnlös anteckning",
  "updated" => "Anteckning uppdaterad.",
  "visibility_description" => "Lägsta roll som krävs för att se denna anteckning."
];
